/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.47
 * Generated at: 2020-07-29 11:34:07 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.sql.Connection;
import java.sql.Date;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.servlet.http.*;
import javax.servlet.*;

public final class welcome_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=ISO-8859-1");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("  ");

   Connection myConn;
   Statement myStmt3;
   Statement myStmt;
   PreparedStatement myStmt1;
   ResultSet myRs2;
   ResultSet myRs;
   ResultSet myRs1;
   String dbUrl = "jdbc:mysql://localhost:3306/bank";
	String user = "sukumar";		
	String pass = "Naveen123";
		
	// 1. Get a connection to database
			myConn = DriverManager.getConnection(dbUrl, user, pass);
			
			
			myStmt = myConn.createStatement();
			int numoftransactions=0;
	         myRs = myStmt.executeQuery("select count(*) as count from transaction_details");
			
			
	         while(myRs.next())
				{
				numoftransactions=myRs.getInt("count");
				}
			int offsetvalue=(numoftransactions-5);
			myStmt1 = myConn.prepareStatement("select *from transaction_details limit ? offset ?");
			myStmt1.setInt(1, 5);
			myStmt1.setInt(2, offsetvalue );
			
			myRs1 = myStmt1.executeQuery();
   
      out.write("\r\n");
      out.write(" <!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("   <head>\r\n");
      out.write("      <title>SELECT Operation</title>\r\n");
      out.write("   </head>\r\n");
      out.write("   \r\n");
      out.write("   <body>\r\n");
      out.write("   <h2><b>Recent Five Transactions are</b></h2>\r\n");
      out.write("     <table border = \"1\">\r\n");
      out.write("         <tr>\r\n");
      out.write("            <th>DateValue</th>\r\n");
      out.write("            <th>Narration</th>\r\n");
      out.write("            <th>Debit</th>\r\n");
      out.write("            <th>Balance</th>\r\n");
      out.write("         </tr>\r\n");
      out.write("            \r\n");
      out.write("        ");
 while(myRs1.next()) {
        	Date date=myRs1.getDate("DateValue");
			String Narration = myRs1.getString("Narration");
			int  debit = myRs1.getInt("Debit");
			int  Balance= myRs1.getInt("Balance");
        	
      out.write("\r\n");
      out.write("            <tr>\r\n");
      out.write("               <td>");
      out.print(date );
      out.write("</td>\r\n");
      out.write("               <td>");
      out.print(Narration );
      out.write("</td>\r\n");
      out.write("               <td>");
      out.print(debit );
      out.write("</td>\r\n");
      out.write("               <td>");
      out.print(Balance );
      out.write("</td>\r\n");
      out.write("            </tr>\r\n");
      out.write("         ");

         } 
         
      out.write("\r\n");
      out.write("       \r\n");
      out.write("      </table>\r\n");
      out.write("   <form action=\"/welcomepage.do\" method=\"post\">\r\n");
      out.write("   <br />\r\n");
      out.write("   <br />\r\n");
      out.write("<input type=\"submit\" value=\"homepage\" /> \r\n");
      out.write("</form>\r\n");
      out.write("   \r\n");
      out.write("   </body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try { out.clearBuffer(); } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
